package co.edu.javeriana.bd.hotel.view;

import co.edu.javeriana.bd.hotel.model.dto.PersonaDTO;
import java.util.List;
import javax.swing.JOptionPane;

public class PanelGestionar extends javax.swing.JPanel {

    /**
     * Creates new form PanelGestionar
     */
    private final Principal principal;
    
    public PanelGestionar(Principal principal) {
        initComponents();
        this.principal = principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        botVolver = new javax.swing.JButton();
        botSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cajaActual = new javax.swing.JTextField();
        cajaNueva = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botCambiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbPersonas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cajaDNI = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cajaDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cajaTelefono = new javax.swing.JTextField();
        botCrearPersona = new javax.swing.JButton();
        botEliminarPersona = new javax.swing.JButton();
        botEliminar = new javax.swing.JButton();
        botAsociar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        botPerAso = new javax.swing.JButton();

        jLabel1.setText("Hotel?");

        titulo.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 153, 153));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        titulo.setText("ReVago");

        botVolver.setBackground(new java.awt.Color(204, 255, 255));
        botVolver.setText("Volver");
        botVolver.setToolTipText("");
        botVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVolverActionPerformed(evt);
            }
        });

        botSalir.setBackground(new java.awt.Color(204, 255, 255));
        botSalir.setText("Cerrar Sesion");
        botSalir.setToolTipText("");
        botSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSalirActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Actual:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Cambiar contraseña");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nueva:");

        cajaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaActualActionPerformed(evt);
            }
        });

        cajaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNuevaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Asociar persona");

        botCambiar.setBackground(new java.awt.Color(255, 255, 204));
        botCambiar.setText("Cambiar");
        botCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCambiarActionPerformed(evt);
            }
        });

        jLabel2.setText("Persona existente");

        jLabel3.setText("DNI");

        jLabel9.setText("Nombre");

        cajaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDNIActionPerformed(evt);
            }
        });

        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });

        jLabel10.setText("Direccion");

        cajaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDireccionActionPerformed(evt);
            }
        });

        jLabel11.setText("Telefono");

        cajaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelefonoActionPerformed(evt);
            }
        });

        botCrearPersona.setBackground(new java.awt.Color(255, 255, 204));
        botCrearPersona.setText("Crear");
        botCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCrearPersonaActionPerformed(evt);
            }
        });

        botEliminarPersona.setBackground(new java.awt.Color(255, 255, 204));
        botEliminarPersona.setText("Eliminar");
        botEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEliminarPersonaActionPerformed(evt);
            }
        });

        botEliminar.setBackground(new java.awt.Color(255, 51, 51));
        botEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botEliminar.setText("Eliminar cuenta");
        botEliminar.setToolTipText("");
        botEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botEliminarActionPerformed(evt);
            }
        });

        botAsociar.setBackground(new java.awt.Color(255, 255, 204));
        botAsociar.setText("Asociar");
        botAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAsociarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setText("Nueva persona");

        botPerAso.setBackground(new java.awt.Color(204, 255, 255));
        botPerAso.setText("Ver persona asociada");
        botPerAso.setToolTipText("");
        botPerAso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPerAsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botVolver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel4)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cajaActual))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cajaNueva)))
                                            .addComponent(botCambiar)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel5)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cmbPersonas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addComponent(botAsociar))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cajaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(botEliminar)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(botEliminarPersona))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel9)
                                                            .addComponent(jLabel3))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cajaDNI)
                                                            .addComponent(cajaNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(cajaDireccion, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 9, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(24, 24, 24))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(botPerAso)
                                                    .addComponent(botCrearPersona))))
                                        .addGap(19, 19, 19)))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botVolver)
                    .addComponent(botSalir))
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(botPerAso)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cajaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cajaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botCambiar)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botAsociar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cajaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cajaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botCrearPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botEliminarPersona)
                    .addComponent(botEliminar))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVolverActionPerformed
        this.principal.irGestionarPaises();
    }//GEN-LAST:event_botVolverActionPerformed

    private void botSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSalirActionPerformed
        this.principal.irGestionarSesion();
    }//GEN-LAST:event_botSalirActionPerformed

    private void cajaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaActualActionPerformed

    private void cajaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNuevaActionPerformed

    private void botCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCambiarActionPerformed
        if(cajaActual.getText().equals("") || cajaNueva.getText().equals("")) JOptionPane.showMessageDialog(null, "Ninguno de los campos puede estar en blanco");
        else
        {
            if(this.principal.cambiarPass(cajaActual.getText(), cajaNueva.getText())) 
                JOptionPane.showMessageDialog(null, "Contraseña actualizada");
            else JOptionPane.showMessageDialog(null, "Contraseña actual incorrecta");
        }
    }//GEN-LAST:event_botCambiarActionPerformed

    private void cajaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDNIActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDireccionActionPerformed

    private void cajaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTelefonoActionPerformed

    private void botCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCrearPersonaActionPerformed
        PersonaDTO p;
        if(cajaDNI.getText().equals("") || cajaNombre.getText().equals("") || cajaDireccion.getText().equals("") || cajaTelefono.getText().equals("")) JOptionPane.showMessageDialog(null, "Ningun campo puede estar vacio");
        else 
        {
            p = new PersonaDTO(cajaDNI.getText(), cajaNombre.getText(), cajaDireccion.getText(), cajaTelefono.getText());
            if(this.principal.crearPersona(p)) JOptionPane.showMessageDialog(null, "Se creo a la persona");
            else JOptionPane.showMessageDialog(null, "No se pudo crear a la persona");
            actPersonas();
        }
    }//GEN-LAST:event_botCrearPersonaActionPerformed

    private void botEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEliminarPersonaActionPerformed
        if(cajaDNI.getText().equals("")) JOptionPane.showMessageDialog(null, "El campo dni no puede estar vacio");
        else 
        {
            if(this.principal.eliminarPersona(cajaDNI.getText())) JOptionPane.showMessageDialog(null, "Se elimino a la persona");
            else JOptionPane.showMessageDialog(null, "No se pudo eliminar a la persona");
            actPersonas();
        }
    }//GEN-LAST:event_botEliminarPersonaActionPerformed

    private void botEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botEliminarActionPerformed
        if(this.principal.eliminarCuenta())
        {
            JOptionPane.showMessageDialog(null, "Cuenta eliminada!");
            this.principal.irGestionarSesion();
        }
        else JOptionPane.showMessageDialog(null, "No se pudo eliminar la cuenta");
    }//GEN-LAST:event_botEliminarActionPerformed

    private void botAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAsociarActionPerformed
        if(this.principal.asociarPersona(cmbPersonas.getSelectedItem().toString().split(" ")[0]))
            JOptionPane.showMessageDialog(null, "Persona asociada a la cuenta");
        else JOptionPane.showMessageDialog(null, "No se pudo asociar la persona a la cuenta");
    }//GEN-LAST:event_botAsociarActionPerformed

    private void botPerAsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPerAsoActionPerformed
        if(this.principal.sesionIniciada.getPersona() != null) JOptionPane.showMessageDialog(null, "Persona asociada: " + this.principal.sesionIniciada.getPersona().toStringAll());
        else JOptionPane.showMessageDialog(null,"Esta cuenta no tiene ninguna persona asociada");
    }//GEN-LAST:event_botPerAsoActionPerformed
    
    protected void actPersonas()
    {
        List<PersonaDTO> personas = this.principal.findAllPersonas();
        for(PersonaDTO p : personas) cmbPersonas.addItem(p.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAsociar;
    private javax.swing.JButton botCambiar;
    private javax.swing.JButton botCrearPersona;
    private javax.swing.JButton botEliminar;
    private javax.swing.JButton botEliminarPersona;
    private javax.swing.JButton botPerAso;
    private javax.swing.JButton botSalir;
    private javax.swing.JButton botVolver;
    private javax.swing.JTextField cajaActual;
    private javax.swing.JTextField cajaDNI;
    private javax.swing.JTextField cajaDireccion;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaNueva;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JComboBox<String> cmbPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
